Rezeptbuch/config/routes.rb
Rezeptbuch::Application.routes.draw do
  resources :quantities

  resources :ingredients

  resources :recipes

  root 'welcome#index'

  

end

Rezeptbuch/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :quantities, inverse_of: :ingredient
	has_many :ingredients, 
         :through => :quantities, inverse_of: :ingredient
end

Rezeptbuch/app/models/quantity.rb
class Quantity < ActiveRecord::Base
	belongs_to :ingredient, inverse_of: :quantities
	belongs_to :recipe, inverse_of: :quantities
end

Rezeptbuch/app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :quantities, inverse_of: :recipe
	has_many :ingredients,
           :through => :quantities, inverse_of: :recipe
end

Rezeptbuch/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rezeptbuch/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ingredient }
      else
        format.html { render action: 'new' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :price)
    end
end

Rezeptbuch/app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  before_action :set_quantity, only: [:show, :edit, :update, :destroy]

  # GET /quantities
  # GET /quantities.json
  def index
    @quantities = Quantity.all
  end

  # GET /quantities/1
  # GET /quantities/1.json
  def show
  end

  # GET /quantities/new
  def new
    @quantity = Quantity.new
  end

  # GET /quantities/1/edit
  def edit
  end

  # POST /quantities
  # POST /quantities.json
  def create
    @quantity = Quantity.new(quantity_params)

    respond_to do |format|
      if @quantity.save
        format.html { redirect_to @quantity, notice: 'Quantity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quantity }
      else
        format.html { render action: 'new' }
        format.json { render json: @quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quantities/1
  # PATCH/PUT /quantities/1.json
  def update
    respond_to do |format|
      if @quantity.update(quantity_params)
        format.html { redirect_to @quantity, notice: 'Quantity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quantities/1
  # DELETE /quantities/1.json
  def destroy
    @quantity.destroy
    respond_to do |format|
      format.html { redirect_to quantities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quantity
      @quantity = Quantity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quantity_params
      params.require(:quantity).permit(:unit, :amount, :recipe_id, :ingredient_id, :recipe, :ingredient)
    end
end

Rezeptbuch/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @quantities = @recipe.quantities.build
  end

  # GET /recipes/1/edit
  def edit
    @quantities = @recipe.quantities
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :instruction, quantities_attributes: [:id, :unit, :amount, :recipe_id, :ingredient_id, :recipe, :ingredient,
    :_destroy])
    end
end

Rezeptbuch/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
    
  	end
end

Rezeptbuch/app/helpers/application_helper.rb
module ApplicationHelper
end

Rezeptbuch/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

Rezeptbuch/app/helpers/quantities_helper.rb
module QuantitiesHelper
end

Rezeptbuch/app/helpers/recipes_helper.rb
module RecipesHelper
end

Rezeptbuch/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Rezeptbuch/app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rezeptbuch/app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

Rezeptbuch/app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price (cent)</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.price %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

Rezeptbuch/app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

Rezeptbuch/app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>
<p>
  <strong>Price (cent):</strong>
  <%= @ingredient.price %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

Rezeptbuch/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rezeptbuch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', '/' %> </br>
<%= yield %>

</body>
</html>

Rezeptbuch/app/views/quantities/_form.html.erb
<%= form_for(@quantity) do |f| %>
  <% if @quantity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quantity.errors.count, "error") %> prohibited this quantity from being saved:</h2>

      <ul>
      <% @quantity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= collection_select(:quantity, :recipe_id, Recipe.all, :id, :title, :prompt => 'Please select a recipe') %>
  </div>
  <div class="field">
    <%= f.label :ingredient_id %><br>
    <%= collection_select(:quantity, :ingredient_id, Ingredient.all, :id, :name, :prompt => 'Please select an ingredient') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rezeptbuch/app/views/quantities/_quantity_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
    <%= f.label :amount, "Amount:" %>
    <%= f.text_field :amount %>
 
    <%= f.fields_for :ingredient do |quantity_ingredient| %>
      <%= quantity_ingredient.text_field :name %>
    <% end %>
 
    
  </div>
</li>

Rezeptbuch/app/views/quantities/edit.html.erb
<h1>Editing quantity</h1>

<%= render 'form' %>

<%= link_to 'Show', @quantity %> |
<%= link_to 'Back', quantities_path %>

Rezeptbuch/app/views/quantities/index.html.erb
<h1>Listing quantities</h1>

<table>
  <thead>
    <tr>
      <th>Unit</th>
      <th>Amount</th>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quantities.each do |quantity| %>
      <tr>
        <td><%= quantity.unit %></td>
        <td><%= quantity.amount %></td>
        <td><%= quantity.recipe_id %></td>
        <td><%= quantity.ingredient_id %></td>
        <td><%= link_to 'Show', quantity %></td>
        <td><%= link_to 'Edit', edit_quantity_path(quantity) %></td>
        <td><%= link_to 'Destroy', quantity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quantity', new_quantity_path %>

Rezeptbuch/app/views/quantities/new.html.erb
<h1>New quantity</h1>

<%= render 'form' %>

<%= link_to 'Back', quantities_path %>

Rezeptbuch/app/views/quantities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unit:</strong>
  <%= @quantity.unit %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @quantity.amount %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @quantity.recipe.title %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @quantity.ingredient.name %>
</p>

<%= link_to 'Edit', edit_quantity_path(@quantity) %> |
<%= link_to 'Back', quantities_path %>

Rezeptbuch/app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
    <% @recipe.errors.full_messages.each do |message| %>
      <div class="alert <%= bootstrap_class_for('error') %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong><%= message %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :title, "Recipe Name", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  </br>
  </br>
  <div class="form-group">
    <%= f.label :description, "A brief description of this recipe", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_area :description, rows: 5, :class => 'form-control' %></div>
  </div>
  </br>
  </br>
  <div class="form-group">
    <%= f.label :instruction, "Instructions for this recipe", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_area :instruction, rows: 10, :class => 'form-control'  %></div>
  </div>
  <%= f.submit %>
<% end %>

Rezeptbuch/app/views/recipes/_quantity_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
    <div class="field">
    <%= attachment_form.label :unit %><br>
    <%= attachment_form.text_field :unit %>
  </div>
  <div class="field">
    <%= attachment_form.label :amount %><br>
    <%= attachment_form.text_field :amount %>
  </div>
  <div class="field">
    <%= attachment_form.label :ingredient_id %><br>
    <%= collection_select(:ingredient_id, Ingredient.all, :id, :name, :prompt => 'Please select an ingredient') %>
  </div>
  <%= attachment_form.link_to_remove "remove" %>
  </div>
</li>

Rezeptbuch/app/views/recipes/edit.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

Rezeptbuch/app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Instruction</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.instruction %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

Rezeptbuch/app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

Rezeptbuch/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Instruction:</strong>
  <%= @recipe.instruction %>
</p>

<p>
  <strong>Ingredients:</strong> </br>
  <% for i in 0..@recipe.quantities.length-1  do %>
  	<%= @recipe.quantities[i].amount %> - <%= @recipe.quantities[i].unit %> - <%= @recipe.quantities[i].ingredient.name %>

  	</br>
  <% end %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

Rezeptbuch/app/views/welcome/index.html.erb
Welcome </br> </br>
<%= link_to 'Recipes', recipes_path %> </br>
<%= link_to 'Ingredients', ingredients_path %> </br>
<%= link_to 'Quantities', quantities_path %> </br>